# Replace the values below with your own
# Rename this file to config.yaml

arxiv:
  categories:
    - cs.AI  # Artificial Intelligence
    - cs.CL  # Computation and Language
    - cs.LG  # Machine Learning
    # - physics.comp-ph  # Computational Physics
  max_results: 100  # Maximum number of papers to fetch per category (0 for no limit)

processor:
  keywords:
    - machine learning
    - natural language processing
    - deep learning
    - neural networks
    - artificial intelligence
  exclusion_keywords:
    - quantum
    - cryptography
    - game theory
    - data mining
  important_words:
    - novel
    - innovative
    - state-of-the-art
  title_keyword_weight: 3
  abstract_keyword_weight: 2
  content_keyword_weight: 1
  exclusion_keyword_penalty: 5
  important_words_weight: 0.5
  min_score: 10

analyzer:
  type: abstract  # abstract | summary
  llm_provider: openai  # gemini | openai

notifier:
  email:
    to: "your_email@example.com"
    from: "sender_email@example.com"
    password: "YOUR_PASSWORD_HERE"
    smtp_server: "smtp.example.com"
    smtp_port: 587  # 465 | 587
    sort_order: alphabetical  # alphabetical | publication_time | relevance

logging:
  level: INFO  # DEBUG | INFO | WARNING | ERROR
  file: paperweight.log  # paperweight.log | /path/to/logfile.log