[project]
name = "paperweight"
version = "0.1.2"
description = "A lightweight RAG implementation."
readme = "README.md"
requires-python = ">=3.11, <3.14"
license = { text = "MIT" }
authors = [{ name = "Sean Brar", email = "hello@seanbrar.com" }]
dependencies = [
    "arxiv==2.1.0",
    "pypdf==4.3.1",
    "psycopg[binary]==3.2.1",
    "python-dotenv==1.0.1",
    "PyYAML==6.0.2",
    "requests==2.31.0",
    "simplerllm==0.3.3.5",
    "tenacity==9.0.0",
    "tiktoken==0.9.0",
]

[project.scripts]
paperweight = "paperweight.main:main"

[project.optional-dependencies]
dev = [
    "html2text==2024.2.26",
    "mypy==1.11.2",
    "pre-commit==3.8.0",
    "pytest==9.0.2",
    "pytest-cov==5.0.0",
    "pytest-mock==3.10.0",
    "ruff==0.6.4",
    "types-PyYAML==6.0.12.20240808",
    "types-requests==2.32.0.20240907",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/paperweight"]

[tool.ruff]
line-length = 88
lint.select = ["F", "E", "W", "C90", "I001", "F401"]
lint.ignore = ["E501"]

# Enable automatic fixing of lint issues
lint.fixable = ["ALL"]
lint.unfixable = ["F401"]

[tool.ruff.format]
# Formatter settings
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.mypy]
mypy_path = "src"

[[tool.mypy.overrides]]
module = "arxiv.*"
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "--strict-markers --cov=paperweight --cov-report=term-missing"
markers = [
    "integration: marks tests as integration tests",
]
testpaths = ["tests"]
pythonpath = ["src"]
